Repository AlJjalTtac/Sparta_3rd_Newsfeed, pull requests merged in 2025-02, with the labels that each got.

#2 [문서] PR template 제작
  .github/pull_request_template.md
Labels: documentation

#1 [문서] Issue template 제작
  .github/ISSUE_TEMPLATE/-기능--구현할-기능-제목.md
  .github/ISSUE_TEMPLATE/-버그--발생한-버그-제목.md
Labels: documentation

#7 회원가입 / 회원탈퇴 기능 구현 / 로그인 기능은 주석처리
  .gitignore
  build.gradle
  src/main/java/com/example/sparta_3rd_newsfeed/Sparta3rdNewsfeedApplication.java
  src/main/java/com/example/sparta_3rd_newsfeed/common/encoder/PasswordEncoder.java
  src/main/java/com/example/sparta_3rd_newsfeed/common/entity/BaseEntity.java
  src/main/java/com/example/sparta_3rd_newsfeed/common/exception/GlobalException.java
  src/main/java/com/example/sparta_3rd_newsfeed/common/filter/AuthFilter.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/controller/MemberController.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/dto/requestDto/DeleteMemberRequestDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/dto/requestDto/LoginRequestDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/dto/requestDto/SignUpRequestDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/dto/responseDto/LoginResponseDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/dto/responseDto/SignUpResponseDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/entity/Member.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/repository/MemberRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: feature

#11 Feat/profile management
  build.gradle
  src/main/java/com/example/sparta_3rd_newsfeed/common/config/SecurityConfig.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/controller/MemberController.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/entity/Member.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/repository/MemberRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/service/MemberService.java
Labels: feature

#14 [기능/미완성] 게시글 CRUD
  src/main/java/com/example/sparta_3rd_newsfeed/feed/README.md
Labels: feature

#17 [기능] 게시글 CRUD 1단계
  src/main/java/com/example/sparta_3rd_newsfeed/feed/README.md
  src/main/java/com/example/sparta_3rd_newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/entity/Feed.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/repository/FeedRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/service/FeedService.java
Labels: feature

#21 [버그] feed 연관관계 매핑
  src/main/java/com/example/sparta_3rd_newsfeed/feed/controller/FeedController.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/controller/LikeController.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/dto/FeedLikeCountDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/dto/FeedRequestDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/entity/Feed.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/entity/Like.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/repository/FeedRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/repository/LikeRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/service/FeedService.java
  src/main/java/com/example/sparta_3rd_newsfeed/feed/service/LikeService.java
  src/main/java/com/example/sparta_3rd_newsfeed/friend/controller/FriendController.java
  src/main/java/com/example/sparta_3rd_newsfeed/friend/dto/response/FriendResponseDto.java
  src/main/java/com/example/sparta_3rd_newsfeed/friend/repository/FriendRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/friend/service/FriendService.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/controller/MemberController.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/entity/Member.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/repository/MemberRepository.java
  src/main/java/com/example/sparta_3rd_newsfeed/member/service/MemberService.java
  src/main/resources/application.properties
Labels: bug, feature
